# 演習5


割り当て 

$$
x =
\begin{pmatrix}
0 \\
1 \\
0 \\
0 \\
1 \\
1
\end{pmatrix}
$$


支払額 

$$
p =
\begin{pmatrix}
0 \\
5 \\
0 \\
0 \\
7 \\
5
\end{pmatrix}
$$



# 演習11

複数需要オークションで割当と,支払い価格を計算する VCG メカニズムを
動的計画法を用いて実装せよ。

## 初期条件

- 誰もいないときは価値ゼロ：

  $$
  V[0, \ell] = 0 \quad (\ell = 0, 1, \ldots, m)
  $$

- 財が 0 個のときも価値ゼロ：

  $$
  V[k, 0] = 0 \quad (k = 0, 1, \ldots, n)
  $$


In [1]:
from typing import List

class cal_dp:
    def __init__(self, n: int, m: int, v: List[int]):
        self.n = n               # number of bidders
        self.m = m               # total units
        self.m_tmp = m           # for backtracking
        self.v = v               # per-unit values (len(v) >= n を想定)
        # DP table: (n+1) x (m+1)
        self.dp = [[0 for _ in range(m + 1)] for _ in range(n + 1)]
        # allocation[i] = units given to bidder i (1-based like DP)
        self.allocation = [0 for _ in range(n + 1)]
        self.resolve_dp()
        self.resolve_backtrack()
        print("Allocation:", self.allocation[1:])  # 1番目以降が実際の人
        print("Max value:", self.dp[self.n][self.m])
        print("DP Table:")
        for row in self.dp:
            print(row)

    def resolve_dp(self):
        # fill dp table
        for i in range(1, self.n + 1):
            for j in range(0, self.m + 1):
                max_val = -1
                # try giving z units to bidder i
                for z in range(0, j + 1):
                    cand = self.dp[i - 1][j - z] + self.v[i - 1] * z
                    if cand > max_val:
                        max_val = cand
                self.dp[i][j] = max_val

        # （デバッグ用）表を見たいならコメントアウト外す
        # for row in self.dp:
        #     print(row)

    def resolve_backtrack(self):
        for i in range(self.n, 0, -1):
            max_val = -1
            allocation = 0
            for z in range(0, self.m_tmp + 1):
                if max_val < self.dp[i - 1][self.m - z] + self.v[i - 1] * z:
                    max_val = self.dp[i - 1][self.m - z] + self.v[i - 1] * z
                    allocation = z

            self.allocation[i] = allocation
            self.m_tmp -= allocation

# 動作確認
cal_dp(3, 4, [1, 2, 3, 4])


Allocation: [0, 0, 4]
Max value: 12
DP Table:
[0, 0, 0, 0, 0]
[0, 1, 2, 3, 4]
[0, 2, 4, 6, 8]
[0, 3, 6, 9, 12]


# 演習12

# 演習13

In [2]:
from typing import List
class MultiUnitVCGAuctionSolver:
    def __init__(self, n: int, m: int,e:List[List[int]], D:List[List[List[int]]]):
        self.n = n               # number of bidders
        self.m = m               # total units
        self.D = D             # D[i][j][k]: bidder i's value for k units when others get j units
        self.e = e               # e[i][j]: bidder i's externality when others get j units
        self.T = [[0 for _ in range(m + 1)] for _ in range(n + 1)]
        self.solve()
    def v_i_x(self,i:int,x:int):
        e_i = self.e[i]
        print(f"e_{i}:",e_i)
        for j in range(len(e_i)):
            if self.D[i][j][0] <= x <= self.D[i][j][1]:
                return e_i[j] * x
        return 0
    def solve(self):
        for i in range(1, self.n + 1):
            for h in range(0, self.m + 1):
                max_val = self.T[i-1][h]
                for z in range(1, h + 1):
                    cand = self.T[i - 1][h - z] + self.v_i_x(i-1,z)
                    if cand > max_val:
                        max_val = cand
                self.T[i][h] = max_val
        print("Total Value Table T:")
        for row in self.T:
            print(row)
                   
            
        
D = [[[1,4],[5,6],[7,9]],
     [[2,3],[4,8],[9,10]],
     [[1,2],[3,5],[6,7]]]
e = [[1,2,3],[2,4,5],[4,6,7]]
MultiUnitVCGAuctionSolver(3,2,e,D)

e_0: [1, 2, 3]
e_0: [1, 2, 3]
e_0: [1, 2, 3]
e_1: [2, 4, 5]
e_1: [2, 4, 5]
e_1: [2, 4, 5]
e_2: [4, 6, 7]
e_2: [4, 6, 7]
e_2: [4, 6, 7]
Total Value Table T:
[0, 0, 0]
[0, 1, 2]
[0, 1, 4]
[0, 4, 8]


# 演習14

# 演習15

クラスHngarianとして実装する

```Python
class Hungarian:
    def __init__(self,X):

```

## 入力X


$$
\mathbf{X}
=
\begin{bmatrix}
x_{1,1} & x_{1,2} & \cdots & x_{1,N} \\
x_{2,1} & x_{2,2} & \cdots & x_{2,N} \\
\vdots  & \vdots  & \ddots & \vdots  \\
x_{N,1} & x_{N,2} & \cdots & x_{N,N}
\end{bmatrix},
\qquad 1 \le i \le N,\; 1 \le j \le N
$$


## step1

## step2

クラスHangarian内にてdef _step(self)として定義する。

## step3

クラスHangarian内にてdef _step3(self)として定義する。

## step4


In [3]:
import numpy as np
from typing import List


class Hungarian:
    N: int  # the dimension of the profit matrix
    tmp_tensor: np.ndarray

    def __init__(self, profit_matrix):
        self.profit_matrix = profit_matrix
        self.cost_matrix = self.create_cost_matrix(profit_matrix)
        self.step1()
        self.ans_pos = self.step_2_3()
        self.ans, self.ans_mat = self.ans_calculation(profit_matrix, self.ans_pos)

    def create_cost_matrix(self, profit_matrix):
        self.N = profit_matrix.shape[0]
        max_value = np.max(profit_matrix)
        return max_value - profit_matrix

    def min_zero_row(self, zero_mat, mark_zero):
        """
        The function can be splitted into two steps:
        #1 The function is used to find the row which containing the fewest 0.
        #2 Select the zero number on the row, and then marked the element corresponding row and column as False
        """

        # Find the row
        min_row = [99999, -1]

        for row_num in range(zero_mat.shape[0]):
            if np.sum(zero_mat[row_num] == True) > 0 and min_row[0] > np.sum(
                zero_mat[row_num] == True
            ):
                min_row = [np.sum(zero_mat[row_num] == True), row_num]

        # Marked the specific row and column as False
        zero_index = np.where(zero_mat[min_row[1]] == True)[0][0]
        mark_zero.append((min_row[1], zero_index))
        zero_mat[min_row[1], :] = False
        zero_mat[:, zero_index] = False

    def mark_matrix(self, mat):
        """
        Finding the returning possible solutions for LAP problem.
        """

        # Transform the matrix to boolean matrix(0 = True, others = False)
        cur_mat = mat
        zero_bool_mat = cur_mat == 0
        zero_bool_mat_copy = zero_bool_mat.copy()

        # Recording possible answer positions by marked_zero
        marked_zero = []
        while True in zero_bool_mat_copy:
            self.min_zero_row(zero_bool_mat_copy, marked_zero)

        # Recording the row and column positions seperately.
        marked_zero_row = []
        marked_zero_col = []
        for i in range(len(marked_zero)):
            marked_zero_row.append(marked_zero[i][0])
            marked_zero_col.append(marked_zero[i][1])

        # Step 2-2-1
        non_marked_row = list(set(range(cur_mat.shape[0])) - set(marked_zero_row))

        marked_cols = []
        check_switch = True
        while check_switch:
            check_switch = False
            for i in range(len(non_marked_row)):
                row_array = zero_bool_mat[non_marked_row[i], :]
                for j in range(row_array.shape[0]):
                    # Step 2-2-2
                    if row_array[j] == True and j not in marked_cols:
                        # Step 2-2-3
                        marked_cols.append(j)
                        check_switch = True

            for row_num, col_num in marked_zero:
                # Step 2-2-4
                if row_num not in non_marked_row and col_num in marked_cols:
                    # Step 2-2-5
                    non_marked_row.append(row_num)
                    check_switch = True
        # Step 2-2-6
        marked_rows = list(set(range(mat.shape[0])) - set(non_marked_row))

        return (marked_zero, marked_rows, marked_cols)

    def step1(self):
        self.tmp_tensor = self.cost_matrix.copy()
        for i in range(self.N):
            min_value = min(self.tmp_tensor[i])
            for j in range(self.N):
                self.tmp_tensor[i][j] -= min_value
        for j in range(self.N):
            col_values = [self.tmp_tensor[i][j] for i in range(self.N)]
            min_value = min(col_values)
            for i in range(self.N):
                self.tmp_tensor[i][j] -= min_value

    def step_2_3(self):
        tmp_tensor = self.tmp_tensor
        num_zero: int = 0
        while num_zero < self.N:
            pos, marked_rows, marked_cols = self.mark_matrix(np.array(tmp_tensor))
            num_zero = len(marked_rows) + len(marked_cols)
            if num_zero < self.N:
                tmp_tensor = self.adjust_matrix(tmp_tensor, marked_rows, marked_cols)
        return pos

    def adjust_matrix(self, mat, cover_rows, cover_cols):
        cur_mat = mat
        non_zero_element = []

        # Step 4-1
        for row in range(len(cur_mat)):
            if row not in cover_rows:
                for i in range(len(cur_mat[row])):
                    if i not in cover_cols:
                        non_zero_element.append(cur_mat[row][i])
        min_num = min(non_zero_element)

        # Step 4-2
        for row in range(len(cur_mat)):
            if row not in cover_rows:
                for i in range(len(cur_mat[row])):
                    if i not in cover_cols:
                        cur_mat[row, i] = cur_mat[row, i] - min_num
        # Step 4-3
        for row in range(len(cover_rows)):
            for col in range(len(cover_cols)):
                cur_mat[cover_rows[row], cover_cols[col]] = (
                    cur_mat[cover_rows[row], cover_cols[col]] + min_num
                )
        return cur_mat

    def ans_calculation(self, mat, pos):
        total = 0
        ans_mat = np.zeros((mat.shape[0], mat.shape[1]))
        for i in range(len(pos)):
            total += mat[pos[i][0], pos[i][1]]
            ans_mat[pos[i][0], pos[i][1]] = mat[pos[i][0], pos[i][1]]
        return total, ans_mat

    def get_answer(self):
        return self.ans, self.ans_mat


def main():

    profit_matrix = np.array([[7, 8, 5, 6], [6, 5, 9, 10], [4, 1, 10, 7], [3, 4, 6, 5]])
    solver = Hungarian(profit_matrix.copy())
    ans, ans_mat = solver.get_answer()
    print(f"Linear Assignment problem result: {ans:.0f}\n{ans_mat}")


if __name__ == "__main__":
    main()

Linear Assignment problem result: 31
[[ 7.  0.  0.  0.]
 [ 0.  0.  0. 10.]
 [ 0.  0. 10.  0.]
 [ 0.  4.  0.  0.]]


# 演習16

ハンガリー法を用いて $(AP)$、$(AP)^{-i}$ を計算する


In [1]:
import numpy as np
from typing import List


class Hungarian:
    N: int  # the dimension of the profit matrix
    tmp_tensor: np.ndarray

    def __init__(self, profit_matrix):
        self.profit_matrix = profit_matrix
        self.cost_matrix = self.create_cost_matrix(profit_matrix)
        self.step1()
        self.ans_pos = self.step_2_3()
        self.ans, self.ans_mat = self.ans_calculation(profit_matrix, self.ans_pos)

    def create_cost_matrix(self, profit_matrix):
        self.N = profit_matrix.shape[0]
        max_value = np.max(profit_matrix)
        return max_value - profit_matrix

    def min_zero_row(self, zero_mat, mark_zero):
        """
        The function can be splitted into two steps:
        #1 The function is used to find the row which containing the fewest 0.
        #2 Select the zero number on the row, and then marked the element corresponding row and column as False
        """

        # Find the row
        min_row = [99999, -1]

        for row_num in range(zero_mat.shape[0]):
            if np.sum(zero_mat[row_num] == True) > 0 and min_row[0] > np.sum(
                zero_mat[row_num] == True
            ):
                min_row = [np.sum(zero_mat[row_num] == True), row_num]

        # Marked the specific row and column as False
        zero_index = np.where(zero_mat[min_row[1]] == True)[0][0]
        mark_zero.append((min_row[1], zero_index))
        zero_mat[min_row[1], :] = False
        zero_mat[:, zero_index] = False

    def mark_matrix(self, mat):
        """
        Finding the returning possible solutions for LAP problem.
        """

        # Transform the matrix to boolean matrix(0 = True, others = False)
        cur_mat = mat
        zero_bool_mat = cur_mat == 0
        zero_bool_mat_copy = zero_bool_mat.copy()

        # Recording possible answer positions by marked_zero
        marked_zero = []
        while True in zero_bool_mat_copy:
            self.min_zero_row(zero_bool_mat_copy, marked_zero)

        # Recording the row and column positions seperately.
        marked_zero_row = []
        marked_zero_col = []
        for i in range(len(marked_zero)):
            marked_zero_row.append(marked_zero[i][0])
            marked_zero_col.append(marked_zero[i][1])

        # Step 2-2-1
        non_marked_row = list(set(range(cur_mat.shape[0])) - set(marked_zero_row))

        marked_cols = []
        check_switch = True
        while check_switch:
            check_switch = False
            for i in range(len(non_marked_row)):
                row_array = zero_bool_mat[non_marked_row[i], :]
                for j in range(row_array.shape[0]):
                    # Step 2-2-2
                    if row_array[j] == True and j not in marked_cols:
                        # Step 2-2-3
                        marked_cols.append(j)
                        check_switch = True

            for row_num, col_num in marked_zero:
                # Step 2-2-4
                if row_num not in non_marked_row and col_num in marked_cols:
                    # Step 2-2-5
                    non_marked_row.append(row_num)
                    check_switch = True
        # Step 2-2-6
        marked_rows = list(set(range(mat.shape[0])) - set(non_marked_row))

        return (marked_zero, marked_rows, marked_cols)

    def step1(self):
        self.tmp_tensor = self.cost_matrix.copy()
        for i in range(self.N):
            min_value = min(self.tmp_tensor[i])
            for j in range(self.N):
                self.tmp_tensor[i][j] -= min_value
        for j in range(self.N):
            col_values = [self.tmp_tensor[i][j] for i in range(self.N)]
            min_value = min(col_values)
            for i in range(self.N):
                self.tmp_tensor[i][j] -= min_value

    def step_2_3(self):
        tmp_tensor = self.tmp_tensor
        num_zero: int = 0
        while num_zero < self.N:
            pos, marked_rows, marked_cols = self.mark_matrix(np.array(tmp_tensor))
            num_zero = len(marked_rows) + len(marked_cols)
            if num_zero < self.N:
                tmp_tensor = self.adjust_matrix(tmp_tensor, marked_rows, marked_cols)
        return pos

    def adjust_matrix(self, mat, cover_rows, cover_cols):
        cur_mat = mat
        non_zero_element = []

        # Step 4-1
        for row in range(len(cur_mat)):
            if row not in cover_rows:
                for i in range(len(cur_mat[row])):
                    if i not in cover_cols:
                        non_zero_element.append(cur_mat[row][i])
        min_num = min(non_zero_element)

        # Step 4-2
        for row in range(len(cur_mat)):
            if row not in cover_rows:
                for i in range(len(cur_mat[row])):
                    if i not in cover_cols:
                        cur_mat[row, i] = cur_mat[row, i] - min_num
        # Step 4-3
        for row in range(len(cover_rows)):
            for col in range(len(cover_cols)):
                cur_mat[cover_rows[row], cover_cols[col]] = (
                    cur_mat[cover_rows[row], cover_cols[col]] + min_num
                )
        return cur_mat

    def ans_calculation(self, mat, pos):
        total = 0
        ans_mat = np.zeros((mat.shape[0], mat.shape[1]))
        for i in range(len(pos)):
            total += mat[pos[i][0], pos[i][1]]
            ans_mat[pos[i][0], pos[i][1]] = mat[pos[i][0], pos[i][1]]
        return total, ans_mat

    def get_answer(self):
        return self.ans, self.ans_mat

In [27]:
from typing import List
import sys
from typing import List


class HungarianVCGAllocator:
    n_bidders: int
    n_items: int
    values: List[List[int]]
    ans_allocation: List[int] = []
    ans_payment: List[int] = []
    x_star: List[List[int]] = []
    x_minus: List[List[List[int]]] = []
    AP: List[List[int]] = []

    def __init__(self, n_bidders: int, n_items: int, values: List[List[int]]):
        self.n_cols = len(values[0])
        self.n_rows = len(values)
        if self.n_cols != n_items or self.n_rows != n_bidders:
            raise ValueError(
                "Dimension of values does not match n_bidders and n_items."
            )
        self.n_bidders = n_bidders
        self.n_items = n_items
        self.values = values
        print("Input values:")
        for row in self.values:
            print(row)
        print("=" * 30)
        _, self.AP = Hungarian(np.array(self.values)).get_answer()
        self.x_star = [
            [1 if self.AP[i][j] != 0 else 0 for j in range(len(self.AP[i]))]
            for i in range(len(self.AP))
        ]
        for i in range(self.n_bidders):
            _, ans_mat = Hungarian(np.array(self.avoid_i(i))).get_answer()
            self.x_minus.append(
                [
                    [1 if ans_mat[k][j] != 0 else 0 for j in range(len(ans_mat[k]))]
                    for k in range(len(ans_mat))
                ]
            )
        
        self.ans_payment = self.cal_payment()
        print("Payments:", self.ans_payment)

    def cal_payment(self) -> List[int]:
        print("Calculating payments...")
        print("=" * 30)
        print("Input values:")
        for row in self.values:
            print(row)
        print("=" * 30)
        print(f"x_star:\n")
        for row in self.x_star:
            print(row)
        print("=" * 30)
        print(f"x_minus:\n")
        for i in range(self.n_bidders):
            print(f"Excluding bidder {i}:\n")
            for row in self.x_minus[i]:
                print(row)
            print("-" * 20)
        payments = []
        for i in range(self.n_bidders):
            value_without_i = 0
            value_with_i = 0
            for k in range(self.n_bidders):
                for j in range(self.n_items):
                    if k != i:
                        value_without_i += self.values[k][j] * self.x_minus[i][k][j]
                        value_with_i += self.values[k][j] * self.x_star[k][j]
            payments.append(value_without_i - value_with_i)
        return payments

    def avoid_i(self, i: int):
        arr = np.array(self.values, dtype=int).copy()
        arr[i, :] = 0
        return arr


# ---- 出力をファイルに保存 ----
sample_n_bidders = 4
sample_n_items = 4
sample_tensor = [[7, 8, 5, 6], [6, 5, 9, 10], [4, 1, 10, 7], [3, 4, 6, 5]]

import sys
from IPython.utils import io

with open("vcg_output.txt", "w", encoding="utf-8") as f:
    with io.capture_output() as captured:
        sys.stdout = f
        test_allocator = HungarianVCGAllocator(
            sample_n_bidders, sample_n_items, sample_tensor
        )
        sys.stdout = sys.__stdout__

print("✅ 出力を 'vcg_output.txt' に保存しました。")


In [29]:
import random
sys.stdout = sys.__stdout__  # 出力先を元に戻す
x = random.randint(10, 50)
print(x)

入札者:10
財の種類:14
評価額:

入札者:10
財の種類:27
評価額:

財の種類:40 

財の種類:33 

財の種類:28 

財の種類:42 

財の種類:46

財の種類:48 

22 

48
